# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: zeros
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
ros_control_namespace: za
hardware_interface:
  joints:
    - za_joint_1
    - za_joint_2
    - za_joint_3
    - za_joint_4
    - za_joint_5
    - za_joint_6
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - za_joint_1
    - za_joint_2
    - za_joint_3
    - za_joint_4
    - za_joint_5
    - za_joint_6
  gains:
    za_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    za_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    za_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    za_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    za_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    za_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
